before:
  hooks:
    - go get -v -d ./...
builds:
  - id: "did-modify"
    binary: did-modify
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64