before:
  hooks:
    - go get -v -d ./...
builds:
  - id: "did-modify"
    binary: did-modify
    main: main.go
    ldflags:
      - -s -w -X github.com/chef/did-modify/commands.version={{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - freebsd_amd64
      - linux_amd64
      - linux_arm64
      - linux_386
      - windows_amd64
      - windows_arm64
