project:
  alias: did-modify

slack:
  notify_channel:
    - releng-notify

pipelines:
  - verify:
      public: true
  - go/build

promote:
  channels:
    - unstable
    - stable

github:
  delete_branch_on_merge: true
  release_branch:
    - main

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
      - trigger_pipeline:go/build:
          post_commit: true
          ignore_labels:
            - "Expeditor: Skip All"
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - bash:.expeditor/create_release.sh